
SYSTEM OF LINEAR EQUATIONS

2X + 3Y = 22

WITH GAUSS SEIDEL METHOD

STEP 1 : CEK/TENTUKAN/BUAT MENJADI DIAGONALLY DOMINANCE DULU

In [1]:
import numpy as np

1 PERSAMAAN LINEAR

In [47]:
a = [[6, 3, 2],
    [2, 7, 3],
    [7, 5, 15]]
# cek duklu apakah diagonally dominance, lalu ambil diagonalnya
print(np.diag(a))
# axis 1 agar jumlahin perbaris, kalau perkolom axis = 0
# jumlahin perbaris dari a
print(np.sum(np.abs(a),axis=1))
# nentunin dengan mengurangi diagonal dengan jumlah perbarisnya
print(np.sum(np.abs(a),axis=1) - (np.diag(a)))


def checkDiagonallyDominance(a):
    diag = np.diag(a)
    sumWithDiag = np.sum(np.abs(a),axis=1)
    sumWithoutDiag = sumWithDiag - diag

    if np.all(diag > sumWithoutDiag):
        print("True")
    else:
        print("false")



checkDiagonallyDominance(a)

[ 6  7 15]
[11 12 27]
[ 5  5 12]
True


In [48]:
a= 0
b = 0
c= 0
epsilon = 0.1
limit = 15
isCompleted = False

oldValue = np.array([a,b,c])

for i in range(1,limit):
    a  = (15 -3*b -2*c)/6
    b= (6 - 2*a - 3*c)/7
    c = (12 - 7*a - 5*b)/15
    newValue = np.array([a,b,c])
    distance = np.sqrt(np.dot(newValue-oldValue, newValue-oldValue))

    if distance < epsilon:
        print("Solution Found")
        isCompleted = True
        break

    oldValue = newValue

if isCompleted == False:
    print("No Solution")

Solution Found


LEBIH DARI 1 SISTEM PERSAMAAN


In [2]:
# ini persamaannya
CaseX = [
  [
    [-3,9,-6],
    [7,-2,-3],
    [4,1,-4]
  ],
  [
    [1, 3, -3, 9],
    [2, -9,3, -3],
    [-1, 3, 15, -1],
   [21, 4, -1, 10]
  ],
  [
    [4,2,-1],
    [1,3,-1],
    [5,2,10]
  ],
  [
    [-7,2,-4],
    [-1,-19,-13],
    [-3,3,-19]
  ],
  [
    [-12, 1, -4, 6],
    [-3, 8,-3, 2],
    [3, 3, 10, -3],
    [3, -2, 3, 12]
  ],
  [
    [2,1,-1],
    [-2,5,-3],
    [-1,-6,-9]
  ]
]

# ini hasilnya dari persamaan diatas, seperti augmented matrix 
CaseY=[
   [0, -6, 5],
   [12, 9, -6, 11],
   [19, 12, 5],
   [8, 3, 5],
   [3, 6, 9, 21],
   [3, 9, 12]
]

In [3]:
def gaussSeidel(x,y,epsilon,limit):
    x = np.array(x)
    y = np.array(y)

    # cek apakah diagonally dominannce
    diag = np.diag(x)
    sumWithDiag = np.sum(np.abs(x),axis=1)
    sumWithoutDiag = sumWithDiag - diag

    if (np.all(diag > sumWithoutDiag)):
        print("True")
    else:
        print("false")
        return False
    
    # untuk ngambil doagonalnya
    diagonal = np.diag(x)
    # pindah ruas
    x = -x
    # hilangin diagonal dengan mengisi dengan 0
    np.fill_diagonal(x,0)

    # untuk mendapatkan jumlah elemen pada x index 0
    oldValue = np.zeros(x.shape[0])

    for i in range(limit):
        newValue = oldValue
        # iterasi sebanyak elemen didalam x
        for j, row in enumerate(x):
            newValue[j] = (y[j] + np.dot(row, newValue))/diagonal[j]
        
        newValue = np.array(newValue)
        distance = np.sqrt(np.dot(newValue-oldValue,newValue-oldValue))

        if distance < epsilon:
            print("Solution Found")
            return True

        oldValue = newValue
    
    return False    

In [4]:
for i, (x,y) in enumerate(zip(CaseX,CaseY)):
    if gaussSeidel(x,y,0.01,15):
        print("Solution Found")
    else:
        print("Solution not Found")

false
Solution not Found
false
Solution not Found
True
Solution Found
Solution Found
false
Solution not Found
false
Solution not Found
false
Solution not Found
